import type { ApprovedVideo, FaqArticle } from "@/features/faq-assistant/types/faq-assistant";

const now = "2026-07-18T00:00:00.000Z";

export const FAQ_SEED_ARTICLES: FaqArticle[] = [
  {
    id: "faq-ecolink-system-overview",
    slug: "ecolink-system-overview",
    title: "EcoLink system workflow",
    category: "ecolink-system",
    content: "EcoLink has four core workflows: AI scan for recyclable-item estimation, partner-center drop-off for verification, points and rewards for incentives, and environment reports for public waste issues. AI outputs are decision support only. Verified points require partner-center confirmation of material and weight.",
    keywords: ["ecolink", "system", "workflow", "scanner", "drop-off", "points", "rewards", "report", "ai", "process"],
    riskLevel: "medium",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-ai-scanner-workflow",
    slug: "ai-scanner-workflow",
    title: "AI scanner workflow",
    category: "ai-scanner",
    content: "The AI scanner accepts one image and returns visible material labels, item types, estimated count, estimated empty weight, confidence, and warnings. Blurry images, dark images, partial views, and contamination reduce confidence. Scanner output is not a verified drop-off record.",
    keywords: ["scanner", "scan", "ai", "image", "photo", "estimate", "confidence", "warnings", "material", "weight"],
    riskLevel: "medium",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-plastic-bottle-prep",
    slug: "plastic-bottle-preparation",
    title: "Plastic bottle preparation",
    category: "plastic",
    content: "Plastic bottles should be emptied, rinsed, and dried before drop-off. Food or liquid residue can contaminate recycling batches. PET and HDPE should be separated when possible. Caps and labels depend on partner-center rules.",
    keywords: ["plastic", "bottle", "pet", "hdpe", "clean", "dry", "recycle", "cap", "label"],
    riskLevel: "low",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-paper-cardboard",
    slug: "paper-cardboard-preparation",
    title: "Paper and cardboard preparation",
    category: "paper-cardboard",
    content: "Paper and cardboard should be dry and free from food or oil. Wet paper, oily pizza boxes, tissue, and laminated paper can reduce recycling quality. Flatten boxes to reduce transport volume.",
    keywords: ["paper", "cardboard", "dry", "oily", "wet", "box", "flatten"],
    riskLevel: "low",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-ewaste-battery",
    slug: "ewaste-and-battery-safety",
    title: "E-waste and battery safety",
    category: "e-waste",
    content: "E-waste, phone batteries, power banks, and laptop batteries should not be mixed with general waste. Swollen, hot, leaking, or damaged batteries should not be crushed, bent, punctured, or handled casually. Use specialist centers or approved campaigns.",
    keywords: ["e-waste", "ewaste", "battery", "phone", "power bank", "hazardous", "leak", "swollen"],
    riskLevel: "high",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-glass-metal",
    slug: "glass-and-metal-preparation",
    title: "Glass and metal preparation",
    category: "glass-metal",
    content: "Glass bottles and metal cans should be empty, rinsed, and dry. Broken glass should be wrapped and clearly marked as sharp. Aerosol cans and chemical containers require partner-center confirmation before drop-off.",
    keywords: ["glass", "metal", "can", "broken", "sharp", "aerosol", "chemical"],
    riskLevel: "medium",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-dropoff-points",
    slug: "dropoff-and-points",
    title: "Drop-off and points guidance",
    category: "drop-off",
    content: "Drop-off flow: prepare and sort material, visit a partner center, show member code or QR, center staff verifies material and weight, then points are recorded. Point values should not be promised before verification.",
    keywords: ["drop-off", "dropoff", "center", "points", "reward", "member code", "qr", "verified", "weight"],
    riskLevel: "medium",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-rewards",
    slug: "rewards-redemption",
    title: "Rewards redemption",
    category: "rewards",
    content: "Reward flow: check points balance, choose an active partner reward, reserve or redeem it, show the claim code to the partner, and mark it fulfilled only after partner acceptance. Stock and partner terms may change.",
    keywords: ["reward", "redeem", "claim code", "points", "partner", "stock", "fulfill"],
    riskLevel: "medium",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-environment-report",
    slug: "environment-report-guidance",
    title: "Environment report guidance",
    category: "environment-report",
    content: "Environment report flow: capture a clear public-place photo, include location and optional note, submit the report, and let AI rate visible dirtiness. Do not touch hazardous waste. The report is an observation until reviewed or acted upon.",
    keywords: ["report", "illegal dumping", "hazardous", "waste", "location", "photo", "dirtiness", "observation"],
    riskLevel: "high",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-recycling-contamination",
    slug: "recycling-contamination-warning-signs",
    title: "Recycling contamination warning signs",
    category: "general-recycling",
    content: "Contamination risks include food residue, wet paper, mixed hazardous waste, broken sharp items, chemical containers, medical waste, and dirty oil containers. When unsure, ask the center before mixing items into a recycling batch.",
    keywords: ["contamination", "dirty", "wet", "food", "chemical", "medical", "hazardous", "oil"],
    riskLevel: "high",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const APPROVED_VIDEO_SEEDS: ApprovedVideo[] = [
  {
    id: "video-plastic-prep-mm",
    title: "Plastic bottle recycling preparation",
    youtubeVideoId: "dQw4w9WgXcQ",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    channelName: "EcoLink Learning",
    category: "plastic",
    tags: ["plastic", "bottle", "pet", "clean", "dry", "recycle"],
    language: "my-en",
    isApproved: true,
    createdAt: now,
  },
  {
    id: "video-ewaste-safety-mm",
    title: "Safe e-waste and battery disposal",
    youtubeVideoId: "M7lc1UVf-VE",
    youtubeUrl: "https://www.youtube.com/watch?v=M7lc1UVf-VE",
    thumbnailUrl: "https://img.youtube.com/vi/M7lc1UVf-VE/hqdefault.jpg",
    channelName: "EcoLink Learning",
    category: "e-waste",
    tags: ["e-waste", "battery", "hazardous", "phone"],
    language: "my-en",
    isApproved: true,
    createdAt: now,
  },
  {
    id: "video-dropoff-rewards-mm",
    title: "EcoLink drop-off and points workflow",
    youtubeVideoId: "ysz5S6PUM-U",
    youtubeUrl: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
    thumbnailUrl: "https://img.youtube.com/vi/ysz5S6PUM-U/hqdefault.jpg",
    channelName: "EcoLink Guide",
    category: "drop-off",
    tags: ["drop-off", "points", "reward", "member code"],
    language: "my",
    isApproved: true,
    createdAt: now,
  },
];
