import type { ApprovedVideo, FaqArticle } from "@/features/faq-assistant/types/faq-assistant";

const now = "2026-07-18T00:00:00.000Z";

export const FAQ_SEED_ARTICLES: FaqArticle[] = [
  {
    id: "faq-ecolink-system-overview",
    slug: "ecolink-system-overview",
    title: "EcoLink system workflow",
    category: "ecolink-system",
    content: "EcoLink has four core workflows: AI scan for recyclable-item estimation, partner-center drop-off for verification, points and rewards for incentives, and environment reports for public waste issues. AI outputs are decision support only. Verified points require partner-center confirmation of material and weight.",
    keywords: ["ecolink", "system", "workflow", "scanner", "drop-off", "points", "rewards", "report", "ai", "process"],
    riskLevel: "medium",
    sourceName: "EcoLink recycle flow",
    sourceUrl: "/recycle",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-ai-scanner-workflow",
    slug: "ai-scanner-workflow",
    title: "AI scanner workflow",
    category: "ai-scanner",
    content: "The AI scanner accepts one image and returns visible material labels, item types, estimated count, estimated empty weight, confidence, and warnings. Blurry images, dark images, partial views, and contamination reduce confidence. Scanner output is not a verified drop-off record.",
    keywords: ["scanner", "scan", "ai", "image", "photo", "estimate", "confidence", "warnings", "material", "weight"],
    riskLevel: "medium",
    sourceName: "EcoLink AI scanner",
    sourceUrl: "/recycle",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-plastic-bottle-prep",
    slug: "plastic-bottle-preparation",
    title: "Plastic bottle preparation",
    category: "plastic",
    content: "Plastic bottles should be emptied, rinsed, and dried before drop-off. Food or liquid residue can contaminate recycling batches. PET and HDPE should be separated when possible. Caps and labels depend on partner-center rules.",
    keywords: ["plastic", "bottle", "pet", "hdpe", "clean", "dry", "recycle", "cap", "label"],
    riskLevel: "low",
    sourceName: "Recycle Now",
    sourceUrl: "https://www.recyclenow.com/recycle-an-item/plastic-bottles",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-recycling-awareness",
    slug: "recycling-awareness-guidance",
    title: "Recycling awareness guidance",
    category: "recycling-awareness",
    content: "To raise recycling awareness, teach one clear behavior at a time: reduce or reuse first, then recycle clean, dry, sorted materials. Use everyday examples such as bottles, cans, paper, and cardboard. Explain that food, liquid, wet paper, hazardous items, and mixed materials can contaminate recycling. Show trusted videos or posters that explain what happens after collection, then connect the lesson to EcoLink scanning and partner-center drop-off.",
    keywords: ["awareness", "aware", "teach", "educate", "education", "people", "community", "campaign", "habit", "clean", "dry", "sort", "contamination", "recycle", "recycling"],
    riskLevel: "low",
    sourceName: "WRAP / Recycle Now",
    sourceUrl: "https://www.wrap.ngo/resources/campaign-assets/recycle-now-how-it-recycled-videos-and-printable-assets",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-reduce-reuse-first",
    slug: "reduce-reuse-before-recycling",
    title: "Reduce and reuse before recycling",
    category: "reduce-reuse",
    content: "The best environmental action is often to reduce waste before it is created, then reuse items before recycling them. Practical actions include buying only what is needed, choosing refillable packaging, using reusable bottles, cups, and bags, repairing usable items, donating usable goods, and repurposing glass, plastic, and cardboard containers before disposal.",
    keywords: ["reduce", "reuse", "re-use", "refill", "repair", "donate", "secondhand", "waste less", "avoid", "reusable", "repurpose"],
    riskLevel: "low",
    sourceName: "Recycle Now",
    sourceUrl: "https://www.recyclenow.com/how-to-recycle/how-to-reduce-waste",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-household-recycling",
    slug: "household-recycling-setup",
    title: "Household recycling setup",
    category: "household-recycling",
    content: "For home recycling, first check what materials your local service or drop-off center accepts, then prepare the right bins or storage area. Keep recyclables clean, dry, and sorted, make sure everyone in the home knows what goes where, and use drop-off points when home collection is unavailable.",
    keywords: ["home", "household", "family", "bin", "bins", "collection", "store", "storage", "drop-off", "clean", "dry", "sorted"],
    riskLevel: "low",
    sourceName: "Recycle Now",
    sourceUrl: "https://www.recyclenow.com/how-to-recycle/household-recycling",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-common-recyclables",
    slug: "common-recyclable-items",
    title: "Common recyclable items",
    category: "common-recyclables",
    content: "Common recyclable household items often include cardboard, paper, food boxes, mail, beverage cans, food cans, glass bottles, jars, jugs, and plastic bottles. Local acceptance still varies, so confirm with the local provider or EcoLink partner center before drop-off.",
    keywords: ["common", "items", "cardboard", "paper", "food boxes", "mail", "beverage cans", "food cans", "glass bottles", "jars", "jugs", "plastic bottles", "curbside"],
    riskLevel: "low",
    sourceName: "US EPA",
    sourceUrl: "https://www.epa.gov/recycle/frequent-questions-recycling",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-paper-cardboard",
    slug: "paper-cardboard-preparation",
    title: "Paper and cardboard preparation",
    category: "paper-cardboard",
    content: "Paper and cardboard should be dry and free from food or oil. Wet paper, oily pizza boxes, tissue, and laminated paper can reduce recycling quality. Flatten boxes to reduce transport volume.",
    keywords: ["paper", "cardboard", "dry", "oily", "wet", "box", "flatten"],
    riskLevel: "low",
    sourceName: "US EPA",
    sourceUrl: "https://www.epa.gov/recycle/how-do-i-recycle-common-recyclables",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-ewaste-battery",
    slug: "ewaste-and-battery-safety",
    title: "E-waste and battery safety",
    category: "e-waste",
    content: "E-waste, phone batteries, power banks, and laptop batteries should not be mixed with general waste. Swollen, hot, leaking, or damaged batteries should not be crushed, bent, punctured, or handled casually. Use specialist centers or approved campaigns.",
    keywords: ["e-waste", "ewaste", "battery", "phone", "power bank", "hazardous", "leak", "swollen"],
    riskLevel: "high",
    sourceName: "US EPA",
    sourceUrl: "https://www.epa.gov/recycle/used-lithium-ion-batteries",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-glass-metal",
    slug: "glass-and-metal-preparation",
    title: "Glass and metal preparation",
    category: "glass-metal",
    content: "Glass bottles and metal cans should be empty, rinsed, and dry. Broken glass should be wrapped and clearly marked as sharp. Aerosol cans and chemical containers require partner-center confirmation before drop-off.",
    keywords: ["glass", "metal", "can", "broken", "sharp", "aerosol", "chemical"],
    riskLevel: "medium",
    sourceName: "US EPA",
    sourceUrl: "https://www.epa.gov/recycle/how-do-i-recycle-common-recyclables",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-dropoff-points",
    slug: "dropoff-and-points",
    title: "Drop-off and points guidance",
    category: "drop-off",
    content: "Drop-off flow: prepare and sort material, visit a partner center, show member code or QR, center staff verifies material and weight, then points are recorded. Point values should not be promised before verification.",
    keywords: ["drop-off", "dropoff", "center", "points", "reward", "member code", "qr", "verified", "weight"],
    riskLevel: "medium",
    sourceName: "EcoLink drop-off",
    sourceUrl: "/recycle",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-rewards",
    slug: "rewards-redemption",
    title: "Rewards redemption",
    category: "rewards",
    content: "Reward flow: check points balance, choose an active partner reward, reserve or redeem it, show the claim code to the partner, and mark it fulfilled only after partner acceptance. Stock and partner terms may change.",
    keywords: ["reward", "redeem", "claim code", "points", "partner", "stock", "fulfill"],
    riskLevel: "medium",
    sourceName: "EcoLink impact",
    sourceUrl: "/dashboard",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-environment-report",
    slug: "environment-report-guidance",
    title: "Environment report guidance",
    category: "environment-report",
    content: "Environment report flow: capture a clear public-place photo, include location and optional note, submit the report, and let AI rate visible dirtiness. Do not touch hazardous waste. The report is an observation until reviewed or acted upon.",
    keywords: ["report", "issue", "waste issue", "illegal dumping", "hazardous", "waste", "location", "photo", "dirtiness", "observation"],
    riskLevel: "high",
    sourceName: "EcoLink report flow",
    sourceUrl: "/report",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-recycling-contamination",
    slug: "recycling-contamination-warning-signs",
    title: "Recycling contamination warning signs",
    category: "general-recycling",
    content: "Contamination risks include food residue, wet paper, mixed hazardous waste, broken sharp items, chemical containers, medical waste, and dirty oil containers. When unsure, ask the center before mixing items into a recycling batch.",
    keywords: ["contamination", "dirty", "wet", "food", "chemical", "medical", "hazardous", "oil", "recycle", "recycling"],
    riskLevel: "high",
    sourceName: "US EPA",
    sourceUrl: "https://www.epa.gov/recycle/how-do-i-recycle-common-recyclables",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "faq-account-progress",
    slug: "account-progress-and-points",
    title: "Account progress and points",
    category: "account-progress",
    content: "EcoGuide cannot see a user's live account, dashboard, approved reports, pending reports, rejected reports, or current points balance from chat alone. Progress should be checked in the EcoLink dashboard. Points come from approved reports or verified drop-offs only, while pending and rejected reports should not increase the points balance.",
    keywords: ["progress", "balance", "impact", "dashboard", "my points", "points", "approved", "pending", "rejected", "reports", "status"],
    riskLevel: "medium",
    sourceName: "EcoLink dashboard",
    sourceUrl: "/dashboard",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const APPROVED_VIDEO_SEEDS: ApprovedVideo[] = [
  {
    id: "video-plastic-prep-mm",
    title: "Plastic bottle recycling preparation",
    youtubeVideoId: "4dz1BLdPsFY",
    youtubeUrl: "https://www.youtube.com/watch?v=4dz1BLdPsFY",
    thumbnailUrl: "https://img.youtube.com/vi/4dz1BLdPsFY/hqdefault.jpg",
    channelName: "Recycle Now",
    category: "plastic",
    tags: ["plastic", "bottle", "pet", "clean", "dry", "recycle"],
    language: "en",
    isApproved: true,
    createdAt: now,
  },
  {
    id: "video-paper-recycling-en",
    title: "Paper recycling process",
    youtubeVideoId: "7mn9RhxS8kg",
    youtubeUrl: "https://www.youtube.com/watch?v=7mn9RhxS8kg",
    thumbnailUrl: "https://img.youtube.com/vi/7mn9RhxS8kg/hqdefault.jpg",
    channelName: "Recycle Now",
    category: "paper-cardboard",
    tags: ["paper", "cardboard", "dry", "recycle", "recycling", "process", "common", "household"],
    language: "en",
    isApproved: true,
    createdAt: now,
  },
  {
    id: "video-cans-recycling-en",
    title: "Metal cans recycling process",
    youtubeVideoId: "t4PLxg06HBU",
    youtubeUrl: "https://www.youtube.com/watch?v=t4PLxg06HBU",
    thumbnailUrl: "https://img.youtube.com/vi/t4PLxg06HBU/hqdefault.jpg",
    channelName: "Recycle Now",
    category: "glass-metal",
    tags: ["metal", "can", "cans", "tin", "recycle", "recycling", "process", "common", "household"],
    language: "en",
    isApproved: true,
    createdAt: now,
  },
  {
    id: "video-weee-recycling-en",
    title: "Small electrical items recycling",
    youtubeVideoId: "RaKLgovVkJQ",
    youtubeUrl: "https://www.youtube.com/watch?v=RaKLgovVkJQ",
    thumbnailUrl: "https://img.youtube.com/vi/RaKLgovVkJQ/hqdefault.jpg",
    channelName: "Recycle Now",
    category: "e-waste",
    tags: ["e-waste", "ewaste", "weee", "electrical", "electronics", "recycle", "recycling"],
    language: "en",
    isApproved: true,
    createdAt: now,
  },
  {
    id: "video-home-recycling-en",
    title: "Recycling around the home",
    youtubeVideoId: "sLktjtlXCNo",
    youtubeUrl: "https://www.youtube.com/watch?v=sLktjtlXCNo",
    thumbnailUrl: "https://img.youtube.com/vi/sLktjtlXCNo/hqdefault.jpg",
    channelName: "Recycle Now",
    category: "general-recycling",
    tags: ["home", "recycle", "recycling", "awareness", "education", "people", "plastic", "paper", "cardboard", "metal", "glass", "electrical"],
    language: "en",
    isApproved: true,
    createdAt: now,
  },
];
